# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleRandomization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N', models.IntegerField()),
                ('seed', models.IntegerField()),
                ('date_created', models.DateField()),
                ('result', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
